name: Vehicle Test Action
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display JSON
        with:
          path: './'

      - uses: actions/checkout@v2
        run: |
          vehicleData=vehicle-data.json >> GITHUB_ENV
          echo "Vehicle: ${{ env.vehicleData }}"
          echo ${{ vehicle-data.json }}
