name: Vehicle Test Action
on:
  push:
    branches: [ master ]
jobs:
  display-data:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2

    steps:

      - name: Display JSON
        with:
          path: './'
      - run: |
          vehicleData=vehicle-data.json >> GITHUB_ENV
          echo "Vehicle: ${{ env.vehicleData }}"
          echo ${{ vehicle-data.json }}
