name: Vehicle Test Action
on:
  push:
    branches: [ master ]
jobs:
  display-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display JSON
        uses: actions/checkout@v2
        with:
          path: './'
        
      - run: echo "hello world!"
      
      - run: |
          echo "vehicleData=$(cat vehicle-data.json)" >> GITHUB_ENV
          echo "Vehicle: ${{ env.vehicleData }}"
