name: Vehicle Test Action
on:
  push:
    branches: [ master ]
jobs:
  display-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Path
        uses: actions/checkout@v2
        with:
          path: './'
        
      - name: Echo vehicle data
        run: cat vehicle.json
      
      - name: Assign to env variable
        run: echo "vehicleData=$(cat vehicle.json)" >> $GITHUB_ENV

      - name: Display Data
        run: echo $vehicleData
